version: 2.1
orbs:
  coverage-reporter: codacy/coverage-reporter@7.6.9

jobs:
  codacy-coverage-report:
    docker:
      - image: 'circleci/openjdk:8-jdk'
    steps:
      - checkout
      - run commands to generate the coverage result
      - coverage-reporter/send_report

  test:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install sphinx pytest 
      - run:
          name: Test
          command: pytest

  docs-build:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install sphinx sphinx_bootstrap_theme pytest numpydoc
      - run:
          name: Build docs
          command: cd docs/ && make html
      - persist_to_workspace:
          root: docs/build
          paths: html
  docs-deploy:
    docker:
      - image: node:10.0.0
    steps:
      - checkout
      - attach_workspace:
          at: docs/build
      - add_ssh_keys:
          fingerprints:
            - "57:78:28:12:8d:ea:c6:4d:05:2f:a2:5e:4f:0b:98:67"
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@concurrent.studio"
            git config user.name "ci-build"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Updates" --dist docs/build/html
    
workflows:
  version: 2
  build:
    jobs:
      - test
      - docs-build
      - docs-deploy:
          requires:
            - test
            - codacy-coverage-report
            - docs-build
          filters:
            branches:
              only: master
